site_name: Tad Zeila Code
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - graph

nav:
  #############################################################################################################################################################
  - üî∞ Dev:
    - About This Page: index.md
    - ‚ó§C√°c Lo·∫°i NNLT:
      - Compiled language: Programming/compiled-language.md
      - Hybrid language: Programming/hybrid-language.md
      - Interpreted language: Programming/interpreted-language.md
      - Non Programming language: NonProgramming/non-programming-language.md
    - ‚ó§Common:
      - Tham Chi·∫øu V√† Tham Tr·ªã: Common/tham-chieu-va-tham-tri.md
      - T·ªëc ƒê·ªô Trong Ng√¥n Ng·ªØ L·∫≠p Tr√¨nh: Common/common-speed-of-language.md
      - L·∫≠p tr√¨nh h∆∞·ªõng ƒë·ªëi t∆∞·ª£ng: Dev/OOP/oop.md
      - Iterators: Common/iterators.md
      - ASCII Table: Common/common-ASCII-table.md
    - ‚ó§DataStruct:
      - Overview: Dev/DataStruct/dev-dataStruct-overview.md
    - ‚ó§Algorithm:
      - Algorithm: Dev/Algorithm/dev-algorithm-overview.md
      - ƒê·ªô ph·ª©c t·∫°p thu·∫≠t to√°n: Dev/Algorithm/dev-algorithm-algorithmic-complexity.md
      - Sorting:
        - About Sort: Dev/Algorithm/dev-algorithm-sort.md
        - Selection Sort: Dev/Algorithm/dev-algorithm-selection-sort.md
        - Bubble Sort: Dev/Algorithm/dev-algorithm-bubble-sort.md
        - Insertion Sort: Dev/Algorithm/dev-algorithm-insertion-sort.md
        - Quick Sort: Dev/Algorithm/dev-algorithm-quick-sort.md
        - Counting Sort: Dev/Algorithm/dev-algorithm-counting-sort.md
      - Hash:
        - FNV1a: Dev/Algorithm/dev-algorithm-hashing-fnv1a.md
      - Wavefunction Collapse: Dev/Algorithm/dev-wavefunction-collapse.md
    - Design Pattern:
      - Overview: Dev/Design_Pattern/dev-design-pattern-overview.md
  #############################################################################################################################################################
  - üî∞ C:
    - C: Programming/c/c.md
    - In/Out: Programming/c/c-in-out.md
    - Note:
      - Makefile: Programming/c/c-makefile.md
  #############################################################################################################################################################
  - üî∞ C++:
    - C++: Programming/cpp/cpp.md
    - ‚ó§C√†i ƒê·∫∑t:
      - Windows: Programming/cpp/cpp-install-for-windows.md
      - Linux: Programming/cpp/cpp-install-for-linux.md
    - ‚ó§Variables:
      - Data Types: Programming/cpp/cpp-primitive-datatypes.md
      - ¬ß Pointer:
        - Pointer: Programming/cpp/cpp-pointer.md
        - Smart Pointer: Programming/cpp/cpp-smart-pointer.md
        - Raw Pointer: Programming/cpp/cpp-raw-pointer.md
      - ¬ß String:
        - String: Programming/cpp/cpp-string.md
        - T·∫°o V√† Hu·ª∑: Programming/cpp/cpp-string-construct-deconstruct.md
        - Truy C·∫≠p: Programming/cpp/cpp-string-index.md
    - ‚ó§Container:
      - Container: Programming/cpp/cpp-container.md
      - Array: Programming/cpp/cpp-array.md
      - Vector: Programming/cpp/cpp-vector.md
      - List: Programming/cpp/cpp-list.md
      - Map: Programming/cpp/cpp-map.md
      - Unordered Map: Programming/cpp/cpp-unordered-map.md
      - Initializer List: Programming/cpp/cpp-initializer-list.md
    - ‚ó§Feature:
      - Math Operator: Programming/cpp/cpp-operator.md
      - Bit Operator: Programming/cpp/cpp-bit-operator.md
      - ƒêi·ªÅu khi·ªÉn lu·ªìng: Programming/cpp/cpp-flow-control.md
      - InOut: Programming/cpp/cpp-in-out.md
      - V√≤ng l·∫∑p: Programming/cpp/cpp-loop.md
      - Function:
        - H√†m: Programming/cpp/cpp-function.md
        - Lambda Function: Programming/cpp/cpp-lambda-function.md
        - Function as Parameter: Programming/cpp/cpp-function-as-parameter.md
    - ‚ó§Ti·ªÅn X·ª≠ L√Ω:
      - Include: Programming/cpp/cpp-include.md
      - Define: Programming/cpp/cpp-define.md
      - Namespace: Programming/cpp/cpp-namespace.md
      - Input Arguments: Programming/cpp/cpp-command-line-arguments.md
      - Memory Model: Programming/cpp/cpp-memory-model.md
      - Named Requirements: Programming/cpp/cpp-named-requirements.md
    - ‚ó§Kh√°i Ni·ªám:
      - Standard Library: Programming/cpp/cpp-std-standard-library.md
      - Iterator:  Programming/cpp/cpp-iterator.md
    - ‚ó§Build:
      - Make Tool: Programming/cpp/cpp-build-tool-make.md
      - Makefile Ex: Programming/cpp/cpp-makefile-example.md
    - ‚ó§Example:
      - Hello World: Programming/cpp/cpp-helloworld.md
    - Refer&Doc: Programming/cpp/cpp-reference-document.md
    # - Discuss:
  #############################################################################################################################################################
  - C#:
    - C#: Programming/c-sharp/c-sharp.md
  #############################################################################################################################################################
  - Rust:
    - Rust: Programming/Rust/rust.md
    - Setup: Programming/Rust/rust-setup.md
    - ‚ó§Example:
      - Hello World: Programming/Rust/rust-example-helloworld.md
      - Variables: Programming/Rust/rust-example-variables.md
      - Primitives: Programming/Rust/rust-example-primitives.md
    - ‚ó§Ph·∫ßn I:
      - Bi·∫øn: Programming/Rust/rust-variables.md
      - Bi·∫øn Ph·ª©c H·ª£p: Programming/Rust/rust-compound-variables.md
      - H√†m: Programming/Rust/rust-function.md
      - Ph∆∞∆°ng Th·ª©c: Programming/Rust/rust-operator.md
      - I/O Printer: Programming/Rust/rust-io-printer.md
      - ƒêi·ªÅu Khi·ªÉn Lu·ªìng: Programming/Rust/rust-flow-control.md
    - Document: Programming/Rust/rust-document.md
  #############################################################################################################################################################
  - Java:
    - Java: Programming/Java/java.md
    - ‚ó§Overview:
      - JDK, JRE v√† JVM: Programming/Java/java-jdk-jre-jvm.md
      - Install: Programming/Java/java-install.md
      - HelloWorld: Programming/Java/java-helloworld.md
    - ‚ó§Basic:
      - Basic Syntax: Programming/Java/java-basic-synctax.md
      - Datatypes & Variables: Programming/Java/java-basic-datatypes-and-variables.md
  #############################################################################################################################################################
  - Javascript:
    - Getting Start: Programming/Javascript/javascript.md
  #############################################################################################################################################################
  - Python:
    - Python: Programming/Python/python.md
    - ‚ó§C√†i ƒë·∫∑t:
      - Window: Programming/Python/python-install-windows.md
      - Resased Version: Programming/Python/python-resased-version.md
      - Any Version: Programming/Python/python-any-version.md
    - ‚ó§C∆° b·∫£n:
      - CƒÉn b·∫£n: Programming/Python/python-basic-concept.md
      - String: Programming/Python/python-string.md
      - To√°n t·ª≠: Programming/Python/python-operator.md
      - ƒêi·ªÅu khi·ªÉn lu·ªìng: Programming/Python/python-control-flow-statements.md
  #############################################################################################################################################################
  - Kotlin:
    - Kotlin: Programming/Kotlin/kotlin.md
    - Basic Concept: Programming/Kotlin/kotlin-basic-tour.md
  #############################################################################################################################################################
  - Web:
    - HTML: NonProgramming/html/html.md
    - CSS: NonProgramming/css/css.md
    - PhP: Programming/php/php.md
  #############################################################################################################################################################
  - Misc.Lang:
    - Markdown: NonProgramming/Markdown/markdown.md
    - Latex: NonProgramming/LaTex/latex.md
    - ‚ó§Katex:
      - Katex: NonProgramming/KaTex/katex.md
      - K√Ω T·ª± To√°n: NonProgramming/KaTex/katex-math-letter.md
      - So S√°nh: NonProgramming/KaTex/katex-math-compare.md
      - Ch·ªØ Hy L·∫°p: NonProgramming/KaTex/katex-greek-letter.md
      - D·∫•u Ngo·∫∑c:  NonProgramming/KaTex/katex-delimiters.md
      - K√≠ch Th∆∞·ªõc:  NonProgramming/KaTex/katex-text-size.md
      - Bi·ªÉu T∆∞·ª£ng V√† D·∫•u: NonProgramming/KaTex/katex-math-symbols-and-punctuation.md
    - ‚ó§PlantUml:
      - PlantUml: NonProgramming/PlantUml/plantuml.md
      - Local Server: NonProgramming/PlantUml/plantuml-local-server.md
      - ¬ß UML Diagrams:
        - Sequence diagram ‚≠ê: NonProgramming/PlantUml/plantuml-sequence-diagram.md
        - Usecase diagram: NonProgramming/PlantUml/plantuml-usecase-diagram.md
        - Class diagram: NonProgramming/PlantUml/plantuml-class-diagram.md
        - Object diagram: NonProgramming/PlantUml/plantuml-object-diagram.md
        - Activity diagram ‚≠ê: NonProgramming/PlantUml/plantuml-activity-diagram.md
        - Component diagram: NonProgramming/PlantUml/plantuml-component-diagram.md
        - Deployment diagram: NonProgramming/PlantUml/plantuml-deployment-diagram.md
        - State diagram: NonProgramming/PlantUml/plantuml-state-diagram.md
        - Timing diagram: NonProgramming/PlantUml/plantuml-timing-diagram.md
      - ¬ß Non-UML Diagrams:
        - JSON data: NonProgramming/PlantUml/plantuml-json-data.md
        - YAML data: NonProgramming/PlantUml/plantuml-yaml-data.md
        - EBNF diagram: NonProgramming/PlantUml/plantuml-ebnf-diagram.md
        - Regex diagram: NonProgramming/PlantUml/plantuml-regex-diagram.md
        - Network diagram (nwdiag): NonProgramming/PlantUml/plantuml-network-diagram-nwdiag.md
        - UI mockups (salt): NonProgramming/PlantUml/plantuml-ui-mockups-salt.md
        - Archimate diagram: NonProgramming/PlantUml/plantuml-archimate-diagram.md
        - SDL: NonProgramming/PlantUml/plantuml-sdl.md
        - Ditaa diagram: NonProgramming/PlantUml/plantuml-ditaa-diagram.md
        - Gantt diagram: NonProgramming/PlantUml/plantuml-gantt-diagram.md
        - Chronology diagram: NonProgramming/PlantUml/plantuml-chronology-diagram.md
        - MindMap diagram ‚≠ê: NonProgramming/PlantUml/plantuml-mindmap-diagram.md
        - WBS diagram ‚≠ê: NonProgramming/PlantUml/plantuml-wbs-diagram.md
        - Mathematics: NonProgramming/PlantUml/plantuml-mathematics.md
        - IE diagram: NonProgramming/PlantUml/plantuml-ie-diagram.md
        - ER diagram: NonProgramming/PlantUml/plantuml-er-diagram.md
    - ‚ó§Mermaid:
      - Mermaid: NonProgramming/Mermaid/mermaid.md
  #############################################################################################################################################################
  - Practice:
    - ‚ó§Prepare: Practice/practice.md
    - ‚ó§Leetcode:
      - Leetcode: Practice/leetcode.md
      - Ô∏æ List: 
        - 1. Two Sum: Practice/leetcode-0001.md
        - 2. Add Two Numbers: Practice/leetcode-0002.md
        - 3. Longest Substring Without Repeating Characters: Practice/leetcode-0003.md
        - 4. Median of Two Sorted Arrays: Practice/leetcode-0004.md
        - 6. Zigzag Conversion: Practice/leetcode-0006.md
        - 7. Reverse Integer: Practice/leetcode-0007.md
        - 8. String to Integer (atoi): Practice/leetcode-0008.md
        - 9. Palindrome Number: Practice/leetcode-0009.md
        - 11. Container With Most Water: Practice/leetcode-0011.md
        - 12. Integer to Roman: Practice/leetcode-0012.md
        - 13. Roman to Integer: Practice/leetcode-0013.md
        - 14. Longest Common Prefix: Practice/leetcode-0014.md
        - 15. 3Sum: Practice/leetcode-0015.md
        - 37. Sudoku Solver: Practice/leetcode-0037.md
        - 39. Combination Sum: Practice/leetcode-0039.md
        - 46. Permutations: Practice/leetcode-0046.md
        - 47. Permutations II: Practice/leetcode-0047.md
        - 1486. 3 XOR Operation in an Array: Practice/leetcode-1486.md
  - Build Tool:
    - Make:
      - Make: Build/make.md
extra_css:
  - assets/stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN