site_name: Tad Code
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - graph

nav:
  #############################################################################################################################################################
  - Computer Sci.:
    - About Computer Science: index.md
    - C√°c Lo·∫°i NNLT:
      - Compiled Language: Programming/compiled-language.md
      - Hybrid Language: Programming/hybrid-language.md
      - Interpreted Language: Programming/interpreted-language.md
      - Non Programming Language: NonProgramming/non-programming-language.md
    - Memory:
      - Heap & Stack: CS/heap-and-stack.md
      - Memory Leaks: CS/common-memory-leaks.md
      - Dangling Pointers: CS/common-dangling-pointers.md
      - L·∫≠p tr√¨nh h∆∞·ªõng ƒë·ªëi t∆∞·ª£ng: Dev/OOP/oop.md
      - Iterators: CS/iterators.md
      - ASCII: CS/common-ASCII.md
    - Programming Paradigms:
      - Programming Paradigms: CS/programming-paradigms.md
      - Tham Chi·∫øu V√† Tham Tr·ªã: CS/tham-chieu-va-tham-tri.md
      - OOP: CD/programming-paradigms-oop.md
    - Tham Kh·∫£o:
      - T·ªëc ƒê·ªô Trong Ng√¥n Ng·ªØ L·∫≠p Tr√¨nh: CS/common-speed-of-language.md
      - Alan Turing: CS/common-alan-turing.md
  #############################################################################################################################################################
  - Data Struct:
    - Data Struct: CS/data-struct.md
    - Linear:
      - Stack: CS/data-struct-stack.md
  - Algorithm:
    - Algorithm: CS/algorithm-overview.md
    - ƒê·ªô ph·ª©c t·∫°p thu·∫≠t to√°n: CS/algorithm-algorithmic-complexity.md
    - Sorting:
      - About Sort: CS/algorithm-sort.md
      - Selection Sort: CS/algorithm-selection-sort.md
      - Bubble Sort: CS/algorithm-bubble-sort.md
      - Insertion Sort: CS/algorithm-insertion-sort.md
      - Quick Sort: CS/algorithm-quick-sort.md
      - Counting Sort: CS/algorithm-counting-sort.md
      - Radix Sort: CS/algorithm-radix-sort.md
    - Hash:
      - Hash:  CS/algorithm-hash.md
      - FNV1a: CS/algorithm-hashing-fnv1a.md
      - Wavefunction Collapse: CS/wavefunction-collapse.md
  - Design Pattern:
    - Design Pattern: CS/design-pattern.md
    - Array: CS/data-struct-array.md
  - C:
    - üáªüá≥ C: Programming/c/c.md
    - Data Types:
      - Data Types: Programming/c/c-data-types.md
      - Derived Data Types: Programming/c/c-derived-data-types.md
      - User Defined Data Types: Programming/c/c-user-defined-data-types.md
      - Chu·ªói: Programming/c/c-array.md
      - Pointer: Programming/c/c-pointer.md
      - (C) Numeric Limits: Programming/c/c-numeric-limits.md
    - In/Out:
      - printf: Programming/c/c-printf.md
      - scanf: Programming/c/c-scanf.md
    - File:
      - fprintf: Programming/c/c-fprintf.md
    - Compiler:
      - Tr√¨nh Bi√™n D·ªãch: Programming/c/c-compiler.md
      - C√°c Giai ƒêo·∫°n: Programming/c/c-translation-phases.md
      - B·ªô Ti·ªÅn X·ª≠ L√Ω: Programming/c/c-preprocessor.md
      - B·ªô Ti·ªÅn X·ª≠ L√Ω: Programming/c/c-replacing-text-macros.md
    - ????:
      - Makefile: Programming/c/c-makefile.md
  #----------------------------------------#
  - C++:
    - Overview:
      - üáªüá≥ C++: Programming/cpp/cpp.md
      - Th∆∞ Vi·ªán STD: Programming/cpp/cpp-std.md
    - C√†i ƒê·∫∑t:
      - Windows: Programming/cpp/cpp-install-for-windows.md
      - Linux: Programming/cpp/cpp-install-for-linux.md
    - Bi·∫øn:
      - Primitive:
        - Primitive‚ùó: Programming/cpp/cpp-primitive-datatypes.md
        - Pointer :
          - Pointer‚ùó: Programming/cpp/cpp-pointer.md
          - Smart Pointer‚ÄºÔ∏è: Programming/cpp/cpp-smart-pointer.md
          - Raw Pointer‚ÄºÔ∏è: Programming/cpp/cpp-raw-pointer.md
        - String:
          - String‚ùó: Programming/cpp/cpp-string.md
          - T·∫°o V√† Hu·ª∑‚ùó: Programming/cpp/cpp-string-construct-deconstruct.md
          - Truy C·∫≠p‚ùó: Programming/cpp/cpp-string-index.md
        - (C++) Numeric Limits‚ùó: Programming/cpp/cpp-std-numeric-limits.md
      - Non Primitive:
        - Bitset‚ÄºÔ∏è: Programming/cpp/cpp-std-bitset.md
    - Container:
      - STD Container: Programming/cpp/cpp-std-container.md
      - STD Linear Types‚ùó: Programming/cpp/cpp-linear-types.md
      - STD Array‚ùó: Programming/cpp/cpp-array.md
      - STD Vector‚ùó: Programming/cpp/cpp-vector.md
      - STD List‚ùó: Programming/cpp/cpp-list.md
      - STD Map‚ÄºÔ∏è: Programming/cpp/cpp-map.md
      - STD Unordered Map‚ÄºÔ∏è: Programming/cpp/cpp-unordered-map.md
      - STD Initializer_List‚ùï: Programming/cpp/cpp-initializer-list.md
      - STD Set‚ùï: Programming/cpp/cpp-set.md
      - STD Unordered Set‚ùï: Programming/cpp/cpp-unordered-set.md
    - Class:
      - Class: Programming/cpp/cpp-class.md
    - Feature:
      - Math Operator‚ùó: Programming/cpp/cpp-operator.md
      - Bit Operator‚ùó: Programming/cpp/cpp-bit-operator.md
      - ƒêi·ªÅu khi·ªÉn lu·ªìng‚ùó: Programming/cpp/cpp-flow-control.md
      - InOut‚ùó: Programming/cpp/cpp-in-out.md
      - V√≤ng l·∫∑p‚ùó: Programming/cpp/cpp-loop.md
    - Function:
      - H√†m‚ùó: Programming/cpp/cpp-function.md
      - Lambda Function‚ÄºÔ∏è: Programming/cpp/cpp-lambda-function.md
      - Function as Parameter‚ÄºÔ∏è: Programming/cpp/cpp-function-as-parameter.md
    - STD Function:
      - STD Iterators‚ÄºÔ∏è: Programming/cpp/cpp-std-iterators.md
      - STD Algorithms‚ÄºÔ∏è: Programming/cpp/cpp-std-algorithms.md
      - STD Math‚ÄºÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD Utility‚ÄºÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD IO‚ÄºÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD System ‚ÅâÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD Chrono ‚ÅâÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD Type_Traits ‚ÅâÔ∏è: Programming/cpp/cpp-std-sort.md
      - STD Format‚ùï: Programming/cpp/cpp-std-sort.md
      - STD Ranges‚ùï: Programming/cpp/cpp-std-sort.md
    - Ti·ªÅn X·ª≠ L√Ω:
      - Include‚ùó: Programming/cpp/cpp-include.md
      - Define‚ùó: Programming/cpp/cpp-define.md
      - Namespace‚ÄºÔ∏è: Programming/cpp/cpp-namespace.md
      - Template‚ÄºÔ∏è: Programming/cpp/cpp-template.md
      - Input Arguments‚ÄºÔ∏è: Programming/cpp/cpp-command-line-arguments.md
      - Memory Model‚ÄºÔ∏è: Programming/cpp/cpp-memory-model.md
      - Named Requirements‚ÄºÔ∏è: Programming/cpp/cpp-named-requirements.md
    - Kh√°i Ni·ªám:
      - Standard Library‚ùó: Programming/cpp/cpp-std-standard-library.md
      - Iterator‚ÄºÔ∏è:  Programming/cpp/cpp-iterator.md
    - Build:
      - Make Tool: Programming/cpp/cpp-build-tool-make.md
      - Makefile Ex: Programming/cpp/cpp-makefile-example.md
    - Refer&Doc: Programming/cpp/cpp-reference-document.md
    - Example:
      - Hello World: Programming/cpp/cpp-helloworld.md
      - My Stack: Programming/cpp/cpp-exmaple-my-stack.md
      - Support Header: Programming/cpp/cpp-exmaple-support-header.md
  #----------------------------------------#
  - Rust:
    - üáªüá≥ Rust: Programming/Rust/rust.md
    - Prepare:
      - Install: Programming/Rust/rust-install.md
      - Prepare for Test: Programming/Rust/rust-prepare-for-test.md
    - Bi·∫øn:
      - Variables: Programming/Rust/rust-variables.md
      - Scalar: Programming/Rust/rust-variables-scalar-types.md
      - Compound: Programming/Rust/rust-variables-compound-types.md
    - H√†m: Programming/Rust/rust-function.md
    - Ph∆∞∆°ng Th·ª©c: Programming/Rust/rust-operator.md
    - I/O Printer: Programming/Rust/rust-io-printer.md
    - ƒêi·ªÅu Khi·ªÉn Lu·ªìng:
      - Flow Control: Programming/Rust/rust-flow-control.md
      - If/Else: Programming/Rust/rust-flow-control-if-else.md
      - Loop: Programming/Rust/rust-flow-control-loop.md
      - While: Programming/Rust/rust-flow-control-while.md
      - For: Programming/Rust/rust-flow-control-for.md
      - Match: Programming/Rust/rust-flow-control-match.md
    - Example:
      - Hello World: Programming/Rust/rust-example-helloworld.md
      - Variables: Programming/Rust/rust-example-variables.md
      - Primitives: Programming/Rust/rust-example-primitives.md
    - Document: Programming/Rust/rust-document.md
  #############################################################################################################################################################
  - Java:
    - üáªüá≥ Java: Programming/Java/java.md
    - Overview:
      - JDK, JRE v√† JVM: Programming/Java/java-jdk-jre-jvm.md
      - Install: Programming/Java/java-install.md
      - HelloWorld: Programming/Java/java-helloworld.md
    - Basic:
      - Basic Syntax: Programming/Java/java-basic-synctax.md
      - Datatypes & Variables: Programming/Java/java-basic-datatypes-and-variables.md
  - Kotlin:
    - üáªüá≥ Kotlin: Programming/Kotlin/kotlin.md
    - Basic Concept: Programming/Kotlin/kotlin-basic-tour.md
  - Python:
    - üáªüá≥ Python: Programming/Python/python.md
    - C√†i ƒë·∫∑t:
      - Window: Programming/Python/python-install-windows.md
      - Resased Version: Programming/Python/python-resased-version.md
      - Any Version: Programming/Python/python-any-version.md
    - C∆° b·∫£n:
      - CƒÉn b·∫£n: Programming/Python/python-basic-concept.md
      - String: Programming/Python/python-string.md
      - To√°n t·ª≠: Programming/Python/python-operator.md
      - ƒêi·ªÅu khi·ªÉn lu·ªìng: Programming/Python/python-control-flow-statements.md
  #############################################################################################################################################################
  - Web:
    - üáªüá≥ HTML: NonProgramming/html/html.md
    - üáªüá≥ CSS: NonProgramming/css/css.md
    - üáªüá≥ PhP: Programming/php/php.md
  #############################################################################################################################################################
  - Another:
    - Another Language: Programming/another-language.md
    - Assembly language: Programming/assembly-language.md
    - Programming language:
      - C#:
        - üáªüá≥ C#: Programming/c-sharp/c-sharp.md
      - Javascript:
        - üáªüá≥ Javascript: Programming/Javascript/javascript.md
    - Non Programming language:
      # - Non Programming language: NonProgramming/non-programming-language.md
      - üáªüá≥ Markdown: NonProgramming/Markdown/markdown.md
      - üáªüá≥ PlantUml:
        - PlantUml: NonProgramming/PlantUml/plantuml.md
        - Local Server: NonProgramming/PlantUml/plantuml-local-server.md
        - UML Diagrams:
          - Sequence diagram ‚öë: NonProgramming/PlantUml/plantuml-sequence-diagram.md
          - Usecase diagram: NonProgramming/PlantUml/plantuml-usecase-diagram.md
          - Class diagram: NonProgramming/PlantUml/plantuml-class-diagram.md
          - Object diagram: NonProgramming/PlantUml/plantuml-object-diagram.md
          - Activity diagram ‚öë: NonProgramming/PlantUml/plantuml-activity-diagram.md
          - Component diagram: NonProgramming/PlantUml/plantuml-component-diagram.md
          - Deployment diagram: NonProgramming/PlantUml/plantuml-deployment-diagram.md
          - State diagram: NonProgramming/PlantUml/plantuml-state-diagram.md
          - Timing diagram: NonProgramming/PlantUml/plantuml-timing-diagram.md
        - Non-UML Diagrams:
          - JSON data: NonProgramming/PlantUml/plantuml-json-data.md
          - YAML data: NonProgramming/PlantUml/plantuml-yaml-data.md
          - EBNF diagram: NonProgramming/PlantUml/plantuml-ebnf-diagram.md
          - Regex diagram: NonProgramming/PlantUml/plantuml-regex-diagram.md
          - Network diagram (nwdiag): NonProgramming/PlantUml/plantuml-network-diagram-nwdiag.md
          - UI mockups (salt): NonProgramming/PlantUml/plantuml-ui-mockups-salt.md
          - Archimate diagram: NonProgramming/PlantUml/plantuml-archimate-diagram.md
          - SDL: NonProgramming/PlantUml/plantuml-sdl.md
          - Ditaa diagram: NonProgramming/PlantUml/plantuml-ditaa-diagram.md
          - Gantt diagram: NonProgramming/PlantUml/plantuml-gantt-diagram.md
          - Chronology diagram: NonProgramming/PlantUml/plantuml-chronology-diagram.md
          - MindMap diagram ‚öë: NonProgramming/PlantUml/plantuml-mindmap-diagram.md
          - WBS diagram ‚öë: NonProgramming/PlantUml/plantuml-wbs-diagram.md
          - Mathematics: NonProgramming/PlantUml/plantuml-mathematics.md
          - IE diagram: NonProgramming/PlantUml/plantuml-ie-diagram.md
          - ER diagram: NonProgramming/PlantUml/plantuml-er-diagram.md
      - üáªüá≥ Mermaid:
        - Mermaid: NonProgramming/Mermaid/mermaid.md
      - üáªüá≥ Matlab:
        - Matlab: Matlab/matlab.md
  #############################################################################################################################################################
  - Practice:
    - Prepare: Practice/practice.md
    - Leetcode:
      - Leetcode: Practice/leetcode.md
      - Leetcode 1-99: Practice/leetcode-1-to-99.md
      - 179. Largest Number: Practice/leetcode-0179.md
      - 1486. 3 XOR Operation in an Array: Practice/leetcode-1486.md
  - Tools:
    - Tools: Tools/tools.md
    - Build Tools:
      - GNU:
        - GNU ‚öë: Tools/tools-gnu.md
        - GCC: Tools/tools-gnu-gcc.md
        - G++: Tools/tools-gnu-g++.md
        - GDB: Tools/tools-gnu-gdb.md
      - LLVM:
        - LLVM ‚öë: Tools/tools-llvm.md
      - Clang:
        - Clang ‚öë: Tools/tools-clang.md
    - Meta-Build System:
      - Meta-Build System: Tools/meta-build-system.md
      - Make:
        - Make: Tools/make.md
        - Install: Tools/make-install.md
        - Example: Tools/make-example.md
      - Cmake:
        - Cmake: Tools/cmake.md

extra_css:
  - assets/stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN

copyright:
  ‚òï Made by Tad Zeila!
